### ISSUE TITLE
feat: WebDAV backup support

### ISSUE THREAD

**Issue by WizDesu** [twofas/2fas-android#172] opened 2024-10-07 21:01 UTC
### Feature description

The idea is to be able to backup our codes to a WebDAV system/server.

### Motivation

I already have a few systems that works fine with WebDAV (for example, Floccus as my bookmark manager to sync all my bookmarks between devices) and I think a WebDAV would be amazing to backup our codes.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by s3rious0** [comment] 2024-10-08 08:51
Hey @WizDesu,

this is an duplicate of #74.

I think you can close this Issue and comment on the other Issue.

Thank you.

Greeting.

**Closed** 2024-10-08 14:00 UTC
Labels: Feature
