### ISSUE TITLE
Other Backup sync options besides Google

### ISSUE THREAD

**Issue by CodeBleu** [twofas/2fas-android#112] opened 2024-02-15 01:03 UTC
I was wondering if there is anything in the works to allow other backup/sync options?

I think it would be nice if this app supported gpg encryption backups that can be synced to a git repo.   Similar to how [Password Store](https://play.google.com/store/apps/details?id=dev.msfjarvis.aps) works

 Even if it's just a non encrypted backup that can be synced to a git repo would be awesome!

I know I can export the backup and manually get it into a git repo, but would be nice if this can just be a nice refresh and it will update new items.  That way you could have multiple devices and easily just setup your git settings and have it do a git pull on refresh,  and git push on a new add 

Curious of others thoughts on this?

**Comment by KobeW50** [comment] 2024-02-22 21:50
Duplicate of https://github.com/twofas/2fas-android/issues/74

Feel free to add your points mentioned in this issue in the comments of #74

**Closed** 2024-02-22 21:50 UTC
Labels: enhancement
