### ISSUE TITLE
Extension pair QR-code not scannable

### ISSUE THREAD

**Issue by Snowpop** [twofas/2fas-android#27] opened 2023-05-07 10:42 UTC
Hello,

On 2FAS Android version 4.5.9 I'm not able to scan the QR-code for the extension. I believe the focus is working, and scanning QR-codes with any other app works perfectly fine.

**Comment by 2fas-com** [comment] 2023-05-19 14:19
It's probably a problem with Samsung phones. It can't be fixed on our side.

**Comment by 2fas-com** [comment] 2023-05-19 15:35
Ok, to specify, after consultation with the dev team, it turns out that the problem is with the "Google ML Kit" scanning library on specific phone models (We've received the most reports about Samsung A23). We are investigating the issue and will resolve it as soon as possible. You can also read about the problem itself here: https://github.com/flutter-ml/google_ml_kit_flutter/issues/285#issuecomment-1297135021.

**Comment by Snowpop** [comment] 2023-05-19 17:46
Ah I see

I assume this workaround doesn't work for your app? https://github.com/flutter-ml/google_ml_kit_flutter/issues/285#issuecomment-1361338064

Anyways, thanks for working on it :)

**Comment by 2fas-com** [comment] 2023-06-30 12:20
As this issue is related to an external library bug, we've decided that for now, we'll add an additional option to simply retype a pairing key. Stay tuned for that!

**Comment by Snowpop** [comment] 2023-06-30 14:48
That would be a good solution!

**Comment by 2fas-com** [comment] 2024-02-14 08:19
We have added the possibility of manual pairing without a QR code.

**Closed by 2fas-com** 2024-02-14 08:19 UTC
